# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d1262169f7b7ca82d741e558831c471f070d17197af189feb95d25eae8de779603e567fbb2e876926fd3b520be2b76ad6350cb177eca6d58e6a6efc1d3c047b

test:
  secret_key_base: 7b12fd21c403c070f39558d2ac7d8832200693d8e51438888426abe366cad4ba7f4fff17cd0b1935cef1a843959470b325601268e79d7954498f0bacf09d6aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
